### ISSUE TITLE
Add dockerfile during release

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt-release#3]
Currently, the dbt release flow:
- adds a requirements file to the dbt repo [here](https://github.com/fishtown-analytics/dbt/tree/dev/kiyoshi-kuromiya/docker/requirements)
- uploads a new image to Docker Hub [here](https://hub.docker.com/r/fishtownanalytics/dbt/tags?page=1&ordering=last_updated)

It does not:
- add a new dockerfile [here](https://github.com/fishtown-analytics/dbt/tree/dev/kiyoshi-kuromiya/docker)

This gives the appearance of our not maintaining docker files / images for each version of dbt, when that's not true. We should either:
- add a dockerfile to the release commit
- if that's not possible, consider removing dockerfiles from the dbt repo, and instead redirecting community members to use the images

**Comment by jtcohen6** [comment]
As possible, let's also backfill the missing dockerfiles for v0.17.0 through v0.19.0

**Comment by jtcohen6** [comment]
Update: Per @kwigley's suggestion, we should just maintain the single simple [Dockerfile](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/Dockerfile) in dbt, not tied to any one specific version. For clarity, we should remove the older versioned Dockerfiles.

We should continue to publish `requirements.txt` that are specific to each version.

**Comment by kwigley** [comment]
@jtcohen6 thanks for the bookkeeping 😄

**Comment by edbizarro** [comment]
are thoses USER_ID and GROUP_ID supported for the old tags like 0.18.1 ?

**Comment by kwigley** [comment]
Cleaned up docker resource in the dbt repo here https://github.com/fishtown-analytics/dbt/pull/3019

Still need to update the dbt-release scripts to use dockerfile in the dbt repo for building and pushing a docker image for releases.

**Comment by kwigley** [comment]
> are those USER_ID and GROUP_ID supported for the old tags like 0.18.1 ?

@edbizarro are you referring to the development docker image?
https://github.com/fishtown-analytics/dbt/blob/1f927a374c8bd52a12a20d892fed9d59cffd04f4/Dockerfile#L53-L57
If so, I believe the answer is yes.

The Dockerfile we use to publish dbt as a docker image to [Docker Hub](https://hub.docker.com/repository/docker/fishtownanalytics/dbt) can be found here https://github.com/fishtown-analytics/dbt/pull/3019/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc.

Does this help with your question?
