### ISSUE TITLE
snowflake-connector-python fails into install from source for Homebrew formula

### ISSUE THREAD

**Issue by kwigley** [fishtown-analytics/dbt-release#5]
A workaround (see https://github.com/fishtown-analytics/dbt-release/pull/4) was put in place to install `snowflake-connector-python` for in the dbt Homebrew formula without build-system dependencies (`--no-pep-517`). I think we will still have to give `snowflake-connector-python` special treatment, but it might be worth not trying to install `snowflake-connector-python` from source. This issue will serve as additional investigation and possible permanent solution for packaging `snowflake-connector-python` as part of the dbt Homebrew release.

**Comment by jtcohen6** [comment]
@kwigley Do you want to keep this one open for further investigation, or should we close it now that we've managed to release v0.19.0 (including Homebrew)?

**Comment by jtcohen6** [comment]
We'll be revisiting this issue (or a version of it) every time we release dbt :) closing for now

**Comment by kwigley** [comment]
https://github.com/fishtown-analytics/dbt-release/pull/14 will force us to revisit this every release
